[platformio]
core_dir=.platformio

[env:sensy_2021_V4_white] ;esp32 old
; Custom board configuration for Sensy 2021 V4 White
platform=espressif32
board=sensy_esp32
framework=arduino
lib_deps=
    paulstoffregen/Time@1.6.1
    https://github.com/carminelau/PMserial.git
    https://github.com/carminelau/SHT21.git
    https://github.com/Sense-Square/SPIlib.git
    https://github.com/DFRobot/DFRobot_OzoneSensor.git
    https://github.com/Seeed-Studio/Seeed_Arduino_MultiGas.git
    https://github.com/bblanchon/ArduinoJson.git
    https://github.com/256dpi/arduino-mqtt.git
    https://github.com/arduino-libraries/ArduinoHttpClient.git
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library.git
    https://github.com/Sensirion/arduino-sps.git
    plerup/EspSoftwareSerial@6.15.2
    https://github.com/Sensirion/arduino-i2c-sen5x.git
    https://github.com/Sensirion/arduino-i2c-scd30.git
    https://github.com/vshymanskyy/TinyGSM.git
    sensirion/Sensirion I2C SCD4x@^1.0.0
    https://github.com/DFRobot/DFRobot_MICS.git
    carminelaudato/hywdc6e-lib
    https://github.com/claws/BH1750.git


build_flags =
    -DYEAR=2021
    -DVERSION=4
    -DARDUINO_ESP32_DEV
    -DMOSI_PIN=13
    -DMISO_PIN=12
    -DSCK_PIN=14
    -DCS_PIN=15
    -DSDA_PIN=21
    -DSCL_PIN=22
    -DTX_PMS_PIN=5
    -DRX_PMS_PIN=4
    -DDI_PIN=26
    -DRO_PIN=32
    -DRE_PIN=33
    -DDE_PIN=25
    -DLED_VOLTAGE=-1
    -DLED_TYPE=-1
    -DRELAY=1
    -DPMS_SET_PIN=27
    -DRELAY1_PIN=18
    -DRELAY2_PIN=19

[env:sensy_2023_V1_green] ;esp32 old
; Custom board configuration for Sensy 2022/23 V1 Green
platform=espressif32
board=sensy_esp32
framework=arduino
lib_deps=
    paulstoffregen/Time@1.6.1
    https://github.com/carminelau/PMserial.git
    https://github.com/carminelau/SHT21.git
    https://github.com/Sense-Square/SPIlib.git
    https://github.com/DFRobot/DFRobot_OzoneSensor.git
    https://github.com/Seeed-Studio/Seeed_Arduino_MultiGas.git
    https://github.com/bblanchon/ArduinoJson.git
    https://github.com/256dpi/arduino-mqtt.git
    https://github.com/arduino-libraries/ArduinoHttpClient.git
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library.git
    https://github.com/Sensirion/arduino-sps.git
    plerup/EspSoftwareSerial@6.15.2
    https://github.com/Sensirion/arduino-i2c-sen5x.git
    https://github.com/Sensirion/arduino-i2c-scd30.git
    https://github.com/vshymanskyy/TinyGSM.git
    sensirion/Sensirion I2C SCD4x@^1.0.0
    https://github.com/DFRobot/DFRobot_MICS.git
    carminelaudato/hywdc6e-lib
    https://github.com/claws/BH1750.git

build_flags =
    -DYEAR=2023
    -DVERSION=1
    -DARDUINO_ESP32_DEV
    -DMOSI_PIN=13
    -DMISO_PIN=12
    -DSCK_PIN=14
    -DCS_PIN=15
    -DSDA_PIN=21
    -DSCL_PIN=22
    -DTX_PMS_PIN=5
    -DRX_PMS_PIN=4
    -DDI_PIN=26
    -DRO_PIN=32
    -DRE_PIN=33
    -DDE_PIN=25
    -DLED_VOLTAGE=-1
    -DLED_TYPE=-1
    -DRELAY=1
    -DPMS_SET_PIN=27
    -DRELAY1_PIN=18
    -DRELAY2_PIN=19
    -DBUTTON_RESET_PIN=23


[env:sensy_2023_V2_black] ;esp32 old
; Custom board configuration for Sensy 2022/23 V2 Black
platform=espressif32
board=sensy_esp32
framework=arduino
lib_deps=
    paulstoffregen/Time@1.6.1
    https://github.com/carminelau/PMserial.git
    https://github.com/carminelau/SHT21.git
    https://github.com/Sense-Square/SPIlib.git
    https://github.com/DFRobot/DFRobot_OzoneSensor.git
    https://github.com/Seeed-Studio/Seeed_Arduino_MultiGas.git
    https://github.com/bblanchon/ArduinoJson.git
    https://github.com/256dpi/arduino-mqtt.git
    https://github.com/arduino-libraries/ArduinoHttpClient.git
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library.git
    https://github.com/Sensirion/arduino-sps.git
    plerup/EspSoftwareSerial@6.15.2
    https://github.com/Sensirion/arduino-i2c-sen5x.git
    https://github.com/Sensirion/arduino-i2c-scd30.git
    https://github.com/vshymanskyy/TinyGSM.git
    sensirion/Sensirion I2C SCD4x@^1.0.0
    https://github.com/DFRobot/DFRobot_MICS.git
    carminelaudato/hywdc6e-lib
    https://github.com/claws/BH1750.git

build_flags =
    -DYEAR=2023
    -DVERSION=2
    -DARDUINO_ESP32_DEV
    -DMOSI_PIN=13
    -DMISO_PIN=12
    -DSCK_PIN=14
    -DCS_PIN=15
    -DSDA_PIN=21
    -DSCL_PIN=22
    -DTX_PMS_PIN=5
    -DRX_PMS_PIN=4
    -DDI_PIN=26
    -DRO_PIN=32
    -DRE_PIN=33
    -DDE_PIN=25
    -DLED_VOLTAGE=3
    -DRELAY=1
    -DPMS_SET_PIN=27
    -DRELAY1_PIN=18
    -DRELAY2_PIN=19
    -DLED_VOLTAGE=-1
    -DLED_TYPE=-1
    -DBUTTON_RESET_PIN=23

[env:sensy_2024_V1_green] ;esp32 new
; Custom board configuration for Sensy 2024 V1 Green
platform=espressif32
board=sensy_esp32s3
framework=arduino
lib_deps=
    paulstoffregen/Time@1.6.1
    https://github.com/carminelau/PMserial.git
    https://github.com/carminelau/SHT21.git
    https://github.com/Sense-Square/SPIlib.git
    https://github.com/DFRobot/DFRobot_OzoneSensor.git
    https://github.com/Seeed-Studio/Seeed_Arduino_MultiGas.git
    https://github.com/bblanchon/ArduinoJson.git
    https://github.com/256dpi/arduino-mqtt.git
    https://github.com/arduino-libraries/ArduinoHttpClient.git
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library.git
    https://github.com/Sensirion/arduino-sps.git
    plerup/EspSoftwareSerial@6.15.2
    https://github.com/Sensirion/arduino-i2c-sen5x.git
    https://github.com/Sensirion/arduino-i2c-scd30.git
    https://github.com/vshymanskyy/TinyGSM.git
    sensirion/Sensirion I2C SCD4x@^1.0.0
    https://github.com/DFRobot/DFRobot_MICS.git
    carminelaudato/hywdc6e-lib
    https://github.com/claws/BH1750.git

build_flags =
    -DYEAR=2024
    -DVERSION=1
    -DARDUINO_ESP32S3_DEV
    -DMOSI_PIN=8
    -DMISO_PIN=16
    -DSCK_PIN=15
    -DCS_PIN=13
    -DSDA_PIN=1
    -DSCL_PIN=2
    -DTX_PMS_PIN=40
    -DRX_PMS_PIN=39
    -DDI_PIN=6
    -DRO_PIN=7
    -DRE_PIN=4
    -DDE_PIN=5
    -DLED_VOLTAGE=3
    -DLED_TYPE=1
    -DRELAY=1
    -DPMS_SET_PIN=14
    -DRELAY1_PIN=41
    -DRELAY2_PIN=42
    -DLEDRGB_PIN=38

[env:sensy_2024_V2_ENEA] ;esp32 new
; Custom board configuration for Sensy 2024 V2 Green (ENEA)
platform=espressif32
board=sensy_esp32s3
framework=arduino
lib_deps=
    paulstoffregen/Time@1.6.1
    https://github.com/carminelau/PMserial.git
    https://github.com/carminelau/SHT21.git
    https://github.com/Sense-Square/SPIlib.git
    https://github.com/DFRobot/DFRobot_OzoneSensor.git
    https://github.com/Seeed-Studio/Seeed_Arduino_MultiGas.git
    https://github.com/bblanchon/ArduinoJson.git
    https://github.com/256dpi/arduino-mqtt.git
    https://github.com/arduino-libraries/ArduinoHttpClient.git
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library.git
    https://github.com/Sensirion/arduino-sps.git
    plerup/EspSoftwareSerial@6.15.2
    https://github.com/Sensirion/arduino-i2c-sen5x.git
    https://github.com/Sensirion/arduino-i2c-scd30.git
    https://github.com/vshymanskyy/TinyGSM.git
    sensirion/Sensirion I2C SCD4x@^1.0.0
    https://github.com/DFRobot/DFRobot_MICS.git
    carminelaudato/hywdc6e-lib
    https://github.com/claws/BH1750.git

build_flags =
    -DYEAR=2024
    -DVERSION=2
    -DENEA
    -DARDUINO_ESP32S3_DEV
    -DMOSI_PIN=17
    -DMISO_PIN=16
    -DSCK_PIN=15
    -DCS_PIN=18
    -DSDA_PIN=8
    -DSCL_PIN=9
    -DTX_PMS_PIN=40
    -DRX_PMS_PIN=39
    -DDI_PIN=-1
    -DRO_PIN=-1
    -DRE_PIN=-1
    -DDE_PIN=-1
    -DLED_VOLTAGE=-1
    -DLED_TYPE=-1
    -DRELAY=1
    -DRELAY1_PIN=41
    -DRELAY2_PIN=42

[env:sensy_2024_V3_red] ;esp32 new
; Custom board configuration for Sensy 2024 V3 Red
platform=espressif32
board=sensy_esp32s3
framework=arduino
lib_deps=
    paulstoffregen/Time@1.6.1
    https://github.com/carminelau/PMserial.git
    https://github.com/carminelau/SHT21.git
    https://github.com/Sense-Square/SPIlib.git
    https://github.com/DFRobot/DFRobot_OzoneSensor.git
    https://github.com/Seeed-Studio/Seeed_Arduino_MultiGas.git
    https://github.com/bblanchon/ArduinoJson.git
    https://github.com/256dpi/arduino-mqtt.git
    https://github.com/arduino-libraries/ArduinoHttpClient.git
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library.git
    https://github.com/Sensirion/arduino-sps.git
    plerup/EspSoftwareSerial@6.15.2
    https://github.com/Sensirion/arduino-i2c-sen5x.git
    https://github.com/Sensirion/arduino-i2c-scd30.git
    https://github.com/vshymanskyy/TinyGSM.git
    sensirion/Sensirion I2C SCD4x@^1.0.0
    https://github.com/DFRobot/DFRobot_MICS.git
    carminelaudato/hywdc6e-lib
    https://github.com/claws/BH1750.git

build_flags =
    -DYEAR=2024
    -DVERSION=3
    -DARDUINO_ESP32S3_DEV
    -DMOSI_PIN=45
    -DMISO_PIN=16
    -DSCK_PIN=15
    -DCS_PIN=13
    -DSDA_PIN=8
    -DSCL_PIN=9
    -DTX_PMS_PIN=40
    -DRX_PMS_PIN=39
    -DDI_PIN=6
    -DRO_PIN=7
    -DRE_PIN=4
    -DDE_PIN=5
    -DLED_VOLTAGE=5
    -DLEDRGB_PIN=38
    -DLED_TYPE=1
    -DRELAY=1
    -DPMS_SET_PIN=14      
    -DRELAY1_PIN=41
    -DRELAY2_PIN=42
    -DBUTTON_RESET_PIN=3

[env:sensy_2024_V4_green] ; esp32 new
; Custom board configuration for Sensy 2024 V4 Green
platform=espressif32
board=sensy_esp32s3
framework=arduino
lib_deps=
    paulstoffregen/Time@1.6.1
    https://github.com/carminelau/PMserial.git
    https://github.com/carminelau/SHT21.git
    https://github.com/Sense-Square/SPIlib.git
    https://github.com/DFRobot/DFRobot_OzoneSensor.git
    https://github.com/Seeed-Studio/Seeed_Arduino_MultiGas.git
    https://github.com/bblanchon/ArduinoJson.git
    https://github.com/256dpi/arduino-mqtt.git
    https://github.com/arduino-libraries/ArduinoHttpClient.git
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library.git
    https://github.com/Sensirion/arduino-sps.git
    #plerup/EspSoftwareSerial@6.15.2
    https://github.com/Sensirion/arduino-i2c-sen5x.git
    https://github.com/Sensirion/arduino-i2c-scd30.git
    https://github.com/vshymanskyy/TinyGSM.git
    sensirion/Sensirion I2C SCD4x@^1.0.0
    https://github.com/DFRobot/DFRobot_MICS.git
    https://github.com/claws/BH1750.git
    https://github.com/carminelau/modbus-sensor-library.git

build_flags =
    -DYEAR=2024
    -DVERSION=4
    -DARDUINO_ESP32S3_DEV
    -DMOSI_PIN=45
    -DMISO_PIN=16
    -DSCK_PIN=15
    -DCS_PIN=13
    -DSDA_PIN=8
    -DSCL_PIN=9
    -DTX_PMS_PIN=40
    -DRX_PMS_PIN=39
    -DDI_PIN=6
    -DRO_PIN=7
    -DRE_PIN=4
    -DDE_PIN=5
    -DLED_VOLTAGE=5
    -DLED_TYPE=2
    -DRELAY=1
    -DLEDRGB_PIN=38
    -DBUTTON_RESET_PIN=3
    -DPMS_SET_PIN=14
    -DRELAY1_PIN=41
    -DRELAY2_PIN=42

[env:sensy_2024_V4_black] ; esp32 new
; Custom board configuration for Sensy 2024 V4 Black
platform=espressif32
board=sensy_esp32s3
framework=arduino
lib_deps=
    paulstoffregen/Time@1.6.1
    https://github.com/carminelau/PMserial.git
    https://github.com/carminelau/SHT21.git
    https://github.com/Sense-Square/SPIlib.git
    https://github.com/DFRobot/DFRobot_OzoneSensor.git
    https://github.com/Seeed-Studio/Seeed_Arduino_MultiGas.git
    https://github.com/bblanchon/ArduinoJson.git
    https://github.com/256dpi/arduino-mqtt.git
    https://github.com/arduino-libraries/ArduinoHttpClient.git
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library.git
    https://github.com/Sensirion/arduino-sps.git
    #plerup/EspSoftwareSerial@6.15.2
    https://github.com/Sensirion/arduino-i2c-sen5x.git
    https://github.com/Sensirion/arduino-i2c-scd30.git
    https://github.com/vshymanskyy/TinyGSM.git
    sensirion/Sensirion I2C SCD4x@^1.0.0
    https://github.com/DFRobot/DFRobot_MICS.git
    https://github.com/claws/BH1750.git
    https://github.com/carminelau/modbus-sensor-library.git

build_flags =
    -DYEAR=2024
    -DVERSION=4
    -DARDUINO_ESP32S3_DEV
    -DMOSI_PIN=45
    -DMISO_PIN=16
    -DSCK_PIN=15
    -DCS_PIN=13
    -DSDA_PIN=8
    -DSCL_PIN=9
    -DTX_PMS_PIN=40
    -DRX_PMS_PIN=39
    -DDI_PIN=6
    -DRO_PIN=7
    -DRE_PIN=4
    -DDE_PIN=5
    -DLED_VOLTAGE=5    
    -DLEDRGB_PIN=38
    -DLED_TYPE=2
    -DRELAY=0
    -DPMS_SET_PIN=14
    -DRELAY1_PIN=41
    -DRELAY2_PIN=42
    -DBUTTON_RESET_PIN=3
