let planId = null;
let remoteReleases = [];
let remoteFirmwares = [];
const $ = (id) => document.getElementById(id);
const strings = {
  it: { heroLead:'Build, registrazione e aggiornamento centraline con piano verificabile.', buildTitle:'Genera release.', branchRelease:'Branch release: BT + incremento automatico.', channel:'Canale', version:'Versione', board:'Board', allBoards:'Tutte board', build:'Build release', registerTitle:'Carica backend.', registerCopy:'File locali devono essere caricati qui prima di comparire nel piano. BT non è default; ST diventa default board.', upload:'Registra firmware selezionati', planTitle:'Seleziona centraline.', planCopy:'Elenco firmware già presenti sul backend.', firmware:'Firmware', refreshFirmware:'Aggiorna elenco firmware', devices:'Centraline · una per riga', force:'Forza solo board assente.', createPlan:'Genera piano', applyTitle:'Conferma update.', planFirst:'Genera prima un piano.', apply:'Assegna firmware OTA', configuration:'CONFIGURAZIONE', settingsTitle:'Parametri dashboard.', apiKey:'API key Sense Square', apiKeyCopy:'Salvata solo nella memoria di questo browser.', projectPath:'Percorso progetto firmware', saveSettings:'Salva configurazione', close:'Chiudi', keyReady:'API KEY · READY', keyMissing:'API KEY · INSERISCI', pathReady:'Progetto disponibile.', pathMissing:'Cartella progetto assente.', buildWorking:'Build in corso. Attendere compilazione.', remoteCount:'Elenco backend aggiornato: {count} firmware.', planReady:'Piano pronto: {count} centraline. Conferma browser per assegnare {firmware}.', confirmApply:'Assegnare firmware OTA alle centraline del piano?', savedSettings:'Configurazione salvata.' },
  en: { heroLead:'Build, register and update devices with a verifiable plan.', buildTitle:'Create release.', branchRelease:'Branch release: BT + automatic increment.', channel:'Channel', version:'Version', board:'Board', allBoards:'All boards', build:'Build release', registerTitle:'Upload to backend.', registerCopy:'Local files must be uploaded here before they appear in the plan. BT is not default; ST becomes board default.', upload:'Register selected firmware', planTitle:'Select devices.', planCopy:'Firmware already available on the backend.', firmware:'Firmware', refreshFirmware:'Refresh firmware list', devices:'Devices · one per line', force:'Force only missing board.', createPlan:'Create plan', applyTitle:'Confirm update.', planFirst:'Create a plan first.', apply:'Assign OTA firmware', configuration:'CONFIGURATION', settingsTitle:'Dashboard settings.', apiKey:'Sense Square API key', apiKeyCopy:'Saved only in this browser storage.', projectPath:'Firmware project path', saveSettings:'Save settings', close:'Close', keyReady:'API KEY · READY', keyMissing:'API KEY · ENTER', pathReady:'Project folder available.', pathMissing:'Project folder missing.', buildWorking:'Build running. Wait for compilation.', remoteCount:'Backend list refreshed: {count} firmware.', planReady:'Plan ready: {count} devices. Confirm in browser to assign {firmware}.', confirmApply:'Assign OTA firmware to devices in this plan?', savedSettings:'Settings saved.' }
};
function language(){ const chosen=$('language').value; return chosen === 'auto' ? (navigator.language || 'it').toLowerCase().startsWith('it') ? 'it' : 'en' : chosen; }
function t(key, values={}){ return Object.entries(values).reduce((text,[name,value])=>text.replace(`{${name}}`,value), strings[language()][key] || key); }
function translate(){ document.documentElement.lang=language(); document.querySelectorAll('[data-i18n]').forEach(node=>node.textContent=t(node.dataset.i18n)); }
const out = (value) => $('output').textContent = typeof value === 'string' ? value : JSON.stringify(value, null, 2);
async function request(path, data) { const res = await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}); const body = await res.json(); if(!res.ok) throw new Error(body.error || 'Request failed'); return body; }
async function get(path) { const res = await fetch(path); const body = await res.json(); if(!res.ok) throw new Error(body.error || 'Request failed'); return body; }
function selectedReleases(){ return [...document.querySelectorAll('.release input:checked')].map(x=>x.value); }
function planFirmware(){ return $('plan-firmware').value; }
function populatePlan(){ const previous=planFirmware(), select=$('plan-firmware'); select.innerHTML=''; for(const name of remoteReleases) select.insertAdjacentHTML('beforeend',`<option value="${name}">${name}</option>`); if(remoteReleases.includes(previous)) select.value=previous; }
function populateBoardFilter(boards){ const select=$('plan-board'), previous=select.value; select.innerHTML='<option value="">Tutte board</option>'; for(const board of boards||[]) select.insertAdjacentHTML('beforeend',`<option value="${board}">${board}</option>`); if([...(select.options)].some(option=>option.value===previous)) select.value=previous; }
function populateFirmwareCatalog(){ const catalog=$('firmware-catalog'); catalog.innerHTML=''; for(const firmware of remoteFirmwares){ const boards=(Array.isArray(firmware.suitable_board)?firmware.suitable_board:[firmware.suitable_board]).filter(Boolean).join(', ') || 'board non indicata'; const defaults=(Array.isArray(firmware.default_board)?firmware.default_board:[firmware.default_board]).filter(Boolean).join(', '); const item=document.createElement('button'); item.type='button'; item.className='firmware-item'; item.innerHTML=`<strong>${esc(firmware.versione)}</strong><span>Compatibile: ${esc(boards)}</span>${defaults?`<span>Default: ${esc(defaults)}</span>`:''}${firmware.note?`<span>${esc(firmware.note)}</span>`:''}`; item.onclick=()=>{ $('plan-firmware').value=firmware.versione; $('centraline').focus(); toast(`Firmware selezionato: ${firmware.versione}`); }; catalog.append(item); } }
function populateLocal(releases){ const list=$('releases'); list.innerHTML=''; for(const name of releases) list.insertAdjacentHTML('beforeend',`<label class="release"><input type="checkbox" value="${name}">${name}</label>`); }
async function refreshBranches(){ const body=await get('/api/branches'); const select=$('build-branch'), previous=select.value; select.innerHTML=''; for(const branch of body.branches) select.insertAdjacentHTML('beforeend',`<option value="${branch}">${branch}</option>`); select.value=body.branches.includes(previous)?previous:body.current_branch; }
async function refresh(){ const status=await get('/api/status'); $('settings').textContent=status.api_key_configured?t('keyReady'):t('keyMissing'); $('project-path').value=status.project_root; $('path-status').textContent=status.project_root_exists?t('pathReady'):t('pathMissing'); populateLocal(status.releases); }
async function refreshRemote(){ const board=$('plan-board').value; const body=await get('/api/remote-firmwares'+(board?`?board=${encodeURIComponent(board)}`:'')); remoteReleases=body.releases; remoteFirmwares=body.firmwares||body.releases.map(versione=>({versione})); populateBoardFilter(body.boards); populatePlan(); populateFirmwareCatalog(); return remoteReleases.length; }
async function restoreBrowserKey(){ const key=localStorage.getItem('ota-dashboard-api-key'); if(key) await request('/api/config',{api_key:key}); }
$('language').value=localStorage.getItem('ota-dashboard-language') || 'auto';
$('language').onchange=()=>{ localStorage.setItem('ota-dashboard-language',$('language').value); translate(); refresh().catch(e=>out('ERROR: '+e.message)); };
$('settings').onclick=()=>{ $('api-key').value=localStorage.getItem('ota-dashboard-api-key') || ''; $('settings-dialog').showModal(); };
$('save-config').onclick=async(event)=>{ event.preventDefault(); try{ const key=$('api-key').value.trim(); if(key) localStorage.setItem('ota-dashboard-api-key',key); const body={project_root:$('project-path').value.trim()}; if(key) body.api_key=key; await request('/api/config',body); $('settings-dialog').close(); await refresh(); await refreshBranches(); await refreshRemote(); out(t('savedSettings')); }catch(e){out('ERROR: '+e.message)} };
$('branch-release').onchange=()=>{ const active=$('branch-release').checked; $('channel').disabled=active; $('version').disabled=active; };
let buildTimer = null;
function buildProgress(start){ let box=$('build-progress'); if(!box){ box=document.createElement('div'); box.id='build-progress'; box.style.cssText='margin-top:14px;padding:12px;border:1px solid #D9E0D3;border-radius:12px;font:12px JetBrains Mono;color:#7C938C'; $('build').after(box); } const tick=()=>{ const seconds=Math.floor((Date.now()-start)/1000); const estimate=$('environment').value ? '2–4 min' : '8–15 min'; box.textContent=`Compilazione in corso · ${seconds}s trascorsi · stima ${estimate}`; }; tick(); buildTimer=setInterval(tick,1000); }
function stopBuildProgress(){ if(buildTimer) clearInterval(buildTimer); buildTimer=null; }
$('build').onclick=async()=>{ const button=$('build'); try{ button.disabled=true; buildProgress(Date.now()); out(t('buildWorking')); const env=$('environment').value; const body=await request('/api/build',{branch:$('build-branch').value,branch_release:$('branch-release').checked,channel:$('channel').value,version:$('version').value,environments:env?[env]:[]}); out(body.output); populateLocal(body.releases); }catch(e){out('ERROR: '+e.message)}finally{stopBuildProgress(); button.disabled=false;} };
$('upload').onclick=async()=>{ try{ const body=await request('/api/upload',{firmwares:selectedReleases()}); await refreshRemote(); out(body); }catch(e){out('ERROR: '+e.message)} };
$('remote-refresh').onclick=async()=>{ try{ out(t('remoteCount',{count:await refreshRemote()})); }catch(e){out('ERROR: '+e.message)} };
$('plan-board').onchange=async()=>{ try{ out(t('remoteCount',{count:await refreshRemote()})); }catch(e){out('ERROR: '+e.message);toast(e.message,true)} };
$('plan').onclick=async()=>{ try{ const centraline=$('centraline').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean); const body=await request('/api/plan',{firmware:planFirmware(),centraline,force:$('force').checked}); planId=body.plan_id; $('apply').disabled=false; $('apply-copy').textContent=t('planReady',{count:body.plan.devices.length,firmware:body.plan.target_firmware}); out(body.plan); }catch(e){out('ERROR: '+e.message)} };
$('apply').onclick=async()=>{ try{ if(!confirm(t('confirmApply'))) return; out(await request('/api/apply',{plan_id:planId})); }catch(e){out('ERROR: '+e.message)} };
document.head.insertAdjacentHTML('beforeend','<style>.language{background:#F3F6EF!important;color:#0B2E2B!important;border-color:#F4C77D!important}.language option{background:#F3F6EF;color:#152521}#build-progress{margin-top:14px;padding:12px;border:1px solid #D9E0D3;border-radius:12px;font:12px JetBrains Mono;color:#7C938C}.progress-track{height:8px;background:#D9E0D3;border-radius:999px;overflow:hidden;margin-top:8px}.progress-fill{height:100%;width:35%;background:#E0902B;animation:build-progress 1.6s infinite}@keyframes build-progress{0%{transform:translateX(-110%)}100%{transform:translateX(320%)}}#toasts{position:fixed;right:22px;bottom:22px;z-index:10;display:grid;gap:10px}.toast{max-width:390px;padding:13px 16px;border-radius:12px;background:#0B2E2B;color:#fff}.toast.error{background:#7b2d2d}</style><div id="toasts"></div>');
function toast(message,error=false){const n=document.createElement('div');n.className='toast'+(error?' error':'');n.textContent=message;$('toasts').append(n);setTimeout(()=>n.remove(),4500)}
let progressTimer=null;
function showProgress(){const start=Date.now();let n=$('build-progress');if(!n){n=document.createElement('div');n.id='build-progress';$('build').after(n)}progressTimer=setInterval(()=>{const s=Math.floor((Date.now()-start)/1000),it=language()==='it',est=$('environment').value?'2–4 min':'8–15 min';n.innerHTML=`${it?'Compilazione in corso':'Build running'} · ${s}s ${it?'trascorsi':'elapsed'} · ${it?'stima':'estimate'} ${est}<div class="progress-track"><div class="progress-fill"></div></div>`},250);}
$('build').onclick=async()=>{const b=$('build');try{b.disabled=true;showProgress();out(t('buildWorking'));const env=$('environment').value;const body=await request('/api/build',{branch:$('build-branch').value,branch_release:$('branch-release').checked,channel:$('channel').value,version:$('version').value,environments:env?[env]:[]});out(body.output);populateLocal(body.releases);toast(language()==='it'?'Build completata.':'Build completed.')}catch(e){out('ERROR: '+e.message);toast(e.message,true)}finally{clearInterval(progressTimer);b.disabled=false}};
translate(); restoreBrowserKey().then(()=>Promise.all([refresh(),refreshBranches(),refreshRemote()])).catch(e=>{out('ERROR dashboard: '+e.message);toast(e.message,true)});
$('branch-release').onchange=()=>{ $('version').disabled=$('branch-release').checked; };
$('channel').disabled=false;
$('version').disabled=$('branch-release').checked;
function autoIncrementLabel(){ document.querySelector('[data-i18n="branchRelease"]').textContent=language()==='it'?'Incremento automatico':'Automatic increment'; }
autoIncrementLabel();
$('language').onchange=()=>{ localStorage.setItem('ota-dashboard-language',$('language').value); translate(); autoIncrementLabel(); refresh().catch(e=>out('ERROR: '+e.message)); };
const uploadButton=$('upload');
uploadButton.insertAdjacentHTML('beforebegin','<label>Note firmware<textarea id="firmware-notes" placeholder="Changelog / funzionalità implementate"></textarea></label><label><input id="update-existing" type="checkbox"> Aggiorna firmware esistente</label><button id="sync-boards" class="secondary" type="button">Sincronizza board da platformio.ini</button>');
$('sync-boards').onclick=async()=>{try{const body=await request('/api/sync-boards',{});out(body);toast('Board sincronizzate.')}catch(e){out('ERROR: '+e.message);toast(e.message,true)}};
$('upload').onclick=async()=>{try{const body=await request('/api/upload',{firmwares:selectedReleases(),notes:$('firmware-notes').value.trim(),update_existing:$('update-existing').checked});await refreshRemote();out(body);toast('Firmware registrato.')}catch(e){out('ERROR: '+e.message);toast(e.message,true)}};
get('/api/release-notes').then(body=>{if(!$('firmware-notes').value)$('firmware-notes').value=body.notes}).catch(()=>{});
$('upload').insertAdjacentHTML('beforebegin','<button id="load-firmware-notes" class="secondary" type="button">Trova note firmware backend</button><label id="existing-firmware-wrap" hidden>Firmware esistente<select id="existing-firmware"></select></label><button id="save-existing-note" class="secondary" type="button" hidden>Salva nota firmware esistente</button>');
$('load-firmware-notes').onclick=async()=>{try{const body=await get('/api/firmware-notes');const s=$('existing-firmware');s.innerHTML='';for(const x of body.firmwares){const n=typeof x==='string'?x:x.versione;if(n)s.insertAdjacentHTML('beforeend',`<option value="${n}">${n}</option>`)}$('existing-firmware-wrap').hidden=false;$('save-existing-note').hidden=false;$('firmware-notes').value=body.suggested_notes;out(body);toast('Note proposte caricate.')}catch(e){out('ERROR: '+e.message);toast(e.message,true)}};
$('save-existing-note').onclick=async()=>{try{const body=await request('/api/firmware-notes',{versione:$('existing-firmware').value,note:$('firmware-notes').value.trim()});out(body);toast('Nota firmware aggiornata.')}catch(e){out('ERROR: '+e.message);toast(e.message,true)}};
let buildStartedAt=0;
function finishProgress(ok){ clearInterval(progressTimer); const seconds=Math.floor((Date.now()-buildStartedAt)/1000); const it=language()==='it'; $('build-progress').innerHTML=`${ok?(it?'Compilazione completata':'Build completed'):(it?'Compilazione fallita':'Build failed')} · ${seconds}s ${it?'totali':'total'}<div class="progress-track"><div class="progress-fill" style="animation:none;transform:translateX(0);width:100%;background:${ok?'#2AA39A':'#9B3131'}"></div></div>`; }
$('build').onclick=async()=>{const b=$('build');let ok=false;try{b.disabled=true;buildStartedAt=Date.now();showProgress();out(t('buildWorking'));const env=$('environment').value;const body=await request('/api/build',{branch:$('build-branch').value,branch_release:$('branch-release').checked,channel:$('channel').value,version:$('version').value,environments:env?[env]:[]});out(body.output);populateLocal(body.releases);ok=true;toast(language()==='it'?'Build completata.':'Build completed.')}catch(e){out('ERROR: '+e.message);toast(e.message,true)}finally{finishProgress(ok);b.disabled=false}};
document.head.insertAdjacentHTML('beforeend','<style>.logButton{background:transparent;border:1px solid #F4C77D;margin:0}.logsDialog{max-width:820px}.logsList{max-height:55vh;overflow:auto;display:grid;gap:8px}.logRow{border-left:3px solid #2AA39A;padding:10px;background:#F3F6EF;font:12px JetBrains Mono}.logRow.error{border-color:#9B3131}.logMeta{color:#7C938C;display:flex;gap:10px;flex-wrap:wrap}</style>');
document.querySelector('.header-actions').insertAdjacentHTML('beforeend','<button id="open-logs" class="chip logButton" type="button">LOG</button><dialog id="logs-dialog" class="logsDialog"><form method="dialog"><p class="kicker">HTTP ACTIVITY</p><h2>Log chiamate.</h2><p id="logs-summary" class="muted"></p><div id="logs-list" class="logsList"></div><menu><button id="refresh-logs" type="button" class="secondary">Aggiorna</button><button id="clear-logs" type="button" class="secondary">Pulisci</button><button>Chiudi</button></menu></form></dialog>');
function esc(v){const n=document.createElement('span');n.textContent=String(v||'');return n.innerHTML}
async function loadLogs(){const p=await get('/api/logs');$('logs-summary').textContent=`${p.total} log · ${p.errors} errori`;$('logs-list').innerHTML=p.logs.length?p.logs.map(x=>`<article class="logRow ${x.ok?'':'error'}"><div class="logMeta"><span>${new Date(x.time).toLocaleTimeString()}</span><strong>${esc(x.type||'DASHBOARD')}</strong><strong>${esc(x.method)}</strong><span>${esc(x.status)}</span><span>${esc(x.duration_ms)} ms</span></div><div class="logRoute">${esc(x.route)}</div>${x.message?`<div class="logMessage">${esc(x.message)}</div>`:''}<details><summary>Parametri inviati</summary><pre>${esc(JSON.stringify(x.params||{},null,2))}</pre></details><details><summary>Risposta</summary><pre>${esc(JSON.stringify(x.response||{},null,2))}</pre></details></article>`).join(''):'Nessun log.';}
$('open-logs').onclick=async()=>{$('logs-dialog').showModal();try{await loadLogs()}catch(e){$('logs-summary').textContent=e.message}};
$('refresh-logs').onclick=()=>loadLogs().catch(e=>{$('logs-summary').textContent=e.message});
$('clear-logs').onclick=async()=>{await fetch('/api/logs',{method:'DELETE'});await loadLogs()};
document.head.insertAdjacentHTML('beforeend','<style>.logRow{color:#152521!important;background:#FBFCF8!important;border:1px solid #D9E0D3!important;border-left:4px solid #2AA39A!important}.logRow.error{border-left-color:#9B3131!important;background:#fff5f3!important}.logMeta{color:#35534c!important;font-weight:600}.logMeta strong{color:#0B2E2B!important;background:#E7EEE3;padding:2px 6px;border-radius:6px}.logRoute{color:#0B2E2B!important;font-weight:700;word-break:break-word;margin:6px 0}.logMessage{color:#7b2d2d!important;font-weight:600}.logRow details{margin-top:7px;border-top:1px solid #D9E0D3;padding-top:6px}.logRow summary{cursor:pointer;color:#0B2E2B;font-weight:700}.logRow pre{background:#0B2E2B;color:#F3F6EF;padding:10px;border-radius:8px;overflow:auto;max-height:220px;white-space:pre-wrap}</style>');
