let planId = null;
let remoteReleases = [];
const $ = (id) => document.getElementById(id);
const strings = {
  it: { heroLead:'Build, registrazione e aggiornamento centraline con piano verificabile.', buildTitle:'Genera release.', branchRelease:'Branch release: BT + incremento automatico.', channel:'Canale', version:'Versione', board:'Board', allBoards:'Tutte board', build:'Build release', registerTitle:'Carica backend.', registerCopy:'File locali devono essere caricati qui prima di comparire nel piano. BT non è default; ST diventa default board.', upload:'Registra firmware selezionati', planTitle:'Seleziona centraline.', planCopy:'Elenco firmware già presenti sul backend.', firmware:'Firmware', refreshFirmware:'Aggiorna elenco firmware', devices:'Centraline · una per riga', force:'Forza solo board assente.', createPlan:'Genera piano', applyTitle:'Conferma update.', planFirst:'Genera prima un piano.', apply:'Assegna firmware OTA', configuration:'CONFIGURAZIONE', settingsTitle:'Parametri dashboard.', apiKey:'API key Sense Square', apiKeyCopy:'Salvata solo nella memoria di questo browser.', projectPath:'Percorso progetto firmware', saveSettings:'Salva configurazione', close:'Chiudi', keyReady:'API KEY · READY', keyMissing:'API KEY · INSERISCI', pathReady:'Progetto disponibile.', pathMissing:'Cartella progetto assente.', buildWorking:'Build in corso. Attendere compilazione.', remoteCount:'Elenco backend aggiornato: {count} firmware.', planReady:'Piano pronto: {count} centraline. Conferma browser per assegnare {firmware}.', confirmApply:'Assegnare firmware OTA alle centraline del piano?', savedSettings:'Configurazione salvata.' },
  en: { heroLead:'Build, register and update devices with a verifiable plan.', buildTitle:'Create release.', branchRelease:'Branch release: BT + automatic increment.', channel:'Channel', version:'Version', board:'Board', allBoards:'All boards', build:'Build release', registerTitle:'Upload to backend.', registerCopy:'Local files must be uploaded here before they appear in the plan. BT is not default; ST becomes board default.', upload:'Register selected firmware', planTitle:'Select devices.', planCopy:'Firmware already available on the backend.', firmware:'Firmware', refreshFirmware:'Refresh firmware list', devices:'Devices · one per line', force:'Force only missing board.', createPlan:'Create plan', applyTitle:'Confirm update.', planFirst:'Create a plan first.', apply:'Assign OTA firmware', configuration:'CONFIGURATION', settingsTitle:'Dashboard settings.', apiKey:'Sense Square API key', apiKeyCopy:'Saved only in this browser storage.', projectPath:'Firmware project path', saveSettings:'Save settings', close:'Close', keyReady:'API KEY · READY', keyMissing:'API KEY · ENTER', pathReady:'Project folder available.', pathMissing:'Project folder missing.', buildWorking:'Build running. Wait for compilation.', remoteCount:'Backend list refreshed: {count} firmware.', planReady:'Plan ready: {count} devices. Confirm in browser to assign {firmware}.', confirmApply:'Assign OTA firmware to devices in this plan?', savedSettings:'Settings saved.' }
};
function language(){ const chosen=$('language').value; return chosen === 'auto' ? (navigator.language || 'it').toLowerCase().startsWith('it') ? 'it' : 'en' : chosen; }
function t(key, values={}){ return Object.entries(values).reduce((text,[name,value])=>text.replace(`{${name}}`,value), strings[language()][key] || key); }
function translate(){ document.documentElement.lang=language(); document.querySelectorAll('[data-i18n]').forEach(node=>node.textContent=t(node.dataset.i18n)); }
const out = (value) => $('output').textContent = typeof value === 'string' ? value : JSON.stringify(value, null, 2);
async function request(path, data) { const res = await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}); const body = await res.json(); if(!res.ok) throw new Error(body.error || 'Request failed'); return body; }
async function get(path) { const res = await fetch(path); const body = await res.json(); if(!res.ok) throw new Error(body.error || 'Request failed'); return body; }
function selectedReleases(){ return [...document.querySelectorAll('.release input:checked')].map(x=>x.value); }
function planFirmware(){ return $('plan-firmware').value; }
function populatePlan(){ const previous=planFirmware(), select=$('plan-firmware'); select.innerHTML=''; for(const name of remoteReleases) select.insertAdjacentHTML('beforeend',`<option value="${name}">${name}</option>`); if(remoteReleases.includes(previous)) select.value=previous; }
function populateLocal(releases){ const list=$('releases'); list.innerHTML=''; for(const name of releases) list.insertAdjacentHTML('beforeend',`<label class="release"><input type="checkbox" value="${name}">${name}</label>`); }
async function refreshBranches(){ const body=await get('/api/branches'); const select=$('build-branch'), previous=select.value; select.innerHTML=''; for(const branch of body.branches) select.insertAdjacentHTML('beforeend',`<option value="${branch}">${branch}</option>`); select.value=body.branches.includes(previous)?previous:body.current_branch; }
async function refresh(){ const status=await get('/api/status'); $('settings').textContent=status.api_key_configured?t('keyReady'):t('keyMissing'); $('project-path').value=status.project_root; $('path-status').textContent=status.project_root_exists?t('pathReady'):t('pathMissing'); populateLocal(status.releases); }
async function refreshRemote(){ const body=await get('/api/remote-firmwares'); remoteReleases=body.releases; populatePlan(); return remoteReleases.length; }
async function restoreBrowserKey(){ const key=localStorage.getItem('ota-dashboard-api-key'); if(key) await request('/api/config',{api_key:key}); }
$('language').value=localStorage.getItem('ota-dashboard-language') || 'auto';
$('language').onchange=()=>{ localStorage.setItem('ota-dashboard-language',$('language').value); translate(); refresh().catch(e=>out('ERROR: '+e.message)); };
$('settings').onclick=()=>{ $('api-key').value=localStorage.getItem('ota-dashboard-api-key') || ''; $('settings-dialog').showModal(); };
$('save-config').onclick=async(event)=>{ event.preventDefault(); try{ const key=$('api-key').value.trim(); if(key) localStorage.setItem('ota-dashboard-api-key',key); const body={project_root:$('project-path').value.trim()}; if(key) body.api_key=key; await request('/api/config',body); $('settings-dialog').close(); await refresh(); await refreshBranches(); await refreshRemote(); out(t('savedSettings')); }catch(e){out('ERROR: '+e.message)} };
$('branch-release').onchange=()=>{ const active=$('branch-release').checked; $('channel').disabled=active; $('version').disabled=active; };
let buildTimer = null;
function buildProgress(start){ let box=$('build-progress'); if(!box){ box=document.createElement('div'); box.id='build-progress'; box.style.cssText='margin-top:14px;padding:12px;border:1px solid #D9E0D3;border-radius:12px;font:12px JetBrains Mono;color:#7C938C'; $('build').after(box); } const tick=()=>{ const seconds=Math.floor((Date.now()-start)/1000); const estimate=$('environment').value ? '2–4 min' : '8–15 min'; box.textContent=`Compilazione in corso · ${seconds}s trascorsi · stima ${estimate}`; }; tick(); buildTimer=setInterval(tick,1000); }
function stopBuildProgress(){ if(buildTimer) clearInterval(buildTimer); buildTimer=null; }
$('build').onclick=async()=>{ const button=$('build'); try{ button.disabled=true; buildProgress(Date.now()); out(t('buildWorking')); const env=$('environment').value; const body=await request('/api/build',{branch:$('build-branch').value,branch_release:$('branch-release').checked,channel:$('channel').value,version:$('version').value,environments:env?[env]:[]}); out(body.output); populateLocal(body.releases); }catch(e){out('ERROR: '+e.message)}finally{stopBuildProgress(); button.disabled=false;} };
$('upload').onclick=async()=>{ try{ const body=await request('/api/upload',{firmwares:selectedReleases()}); await refreshRemote(); out(body); }catch(e){out('ERROR: '+e.message)} };
$('remote-refresh').onclick=async()=>{ try{ out(t('remoteCount',{count:await refreshRemote()})); }catch(e){out('ERROR: '+e.message)} };
$('plan').onclick=async()=>{ try{ const centraline=$('centraline').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean); const body=await request('/api/plan',{firmware:planFirmware(),centraline,force:$('force').checked}); planId=body.plan_id; $('apply').disabled=false; $('apply-copy').textContent=t('planReady',{count:body.plan.devices.length,firmware:body.plan.target_firmware}); out(body.plan); }catch(e){out('ERROR: '+e.message)} };
$('apply').onclick=async()=>{ try{ if(!confirm(t('confirmApply'))) return; out(await request('/api/apply',{plan_id:planId})); }catch(e){out('ERROR: '+e.message)} };
document.head.insertAdjacentHTML('beforeend','<style>.language{background:#F3F6EF!important;color:#0B2E2B!important;border-color:#F4C77D!important}.language option{background:#F3F6EF;color:#152521}#build-progress{margin-top:14px;padding:12px;border:1px solid #D9E0D3;border-radius:12px;font:12px JetBrains Mono;color:#7C938C}.progress-track{height:8px;background:#D9E0D3;border-radius:999px;overflow:hidden;margin-top:8px}.progress-fill{height:100%;width:35%;background:#E0902B;animation:build-progress 1.6s infinite}@keyframes build-progress{0%{transform:translateX(-110%)}100%{transform:translateX(320%)}}#toasts{position:fixed;right:22px;bottom:22px;z-index:10;display:grid;gap:10px}.toast{max-width:390px;padding:13px 16px;border-radius:12px;background:#0B2E2B;color:#fff}.toast.error{background:#7b2d2d}</style><div id="toasts"></div>');
function toast(message,error=false){const n=document.createElement('div');n.className='toast'+(error?' error':'');n.textContent=message;$('toasts').append(n);setTimeout(()=>n.remove(),4500)}
let progressTimer=null;
function showProgress(){const start=Date.now();let n=$('build-progress');if(!n){n=document.createElement('div');n.id='build-progress';$('build').after(n)}progressTimer=setInterval(()=>{const s=Math.floor((Date.now()-start)/1000),it=language()==='it',est=$('environment').value?'2–4 min':'8–15 min';n.innerHTML=`${it?'Compilazione in corso':'Build running'} · ${s}s ${it?'trascorsi':'elapsed'} · ${it?'stima':'estimate'} ${est}<div class="progress-track"><div class="progress-fill"></div></div>`},250);}
$('build').onclick=async()=>{const b=$('build');try{b.disabled=true;showProgress();out(t('buildWorking'));const env=$('environment').value;const body=await request('/api/build',{branch:$('build-branch').value,branch_release:$('branch-release').checked,channel:$('channel').value,version:$('version').value,environments:env?[env]:[]});out(body.output);populateLocal(body.releases);toast(language()==='it'?'Build completata.':'Build completed.')}catch(e){out('ERROR: '+e.message);toast(e.message,true)}finally{clearInterval(progressTimer);b.disabled=false}};
translate(); restoreBrowserKey().then(()=>Promise.all([refresh(),refreshBranches(),refreshRemote()])).catch(e=>{out('ERROR dashboard: '+e.message);toast(e.message,true)});
$('branch-release').onchange=()=>{ $('version').disabled=$('branch-release').checked; };
$('channel').disabled=false;
$('version').disabled=$('branch-release').checked;
function autoIncrementLabel(){ document.querySelector('[data-i18n="branchRelease"]').textContent=language()==='it'?'Incremento automatico':'Automatic increment'; }
autoIncrementLabel();
$('language').onchange=()=>{ localStorage.setItem('ota-dashboard-language',$('language').value); translate(); autoIncrementLabel(); refresh().catch(e=>out('ERROR: '+e.message)); };
