let planId = null;
let remoteReleases = [];
const $ = (id) => document.getElementById(id);
const strings = {
  it: { heroLead:'Build, registrazione e aggiornamento centraline con piano verificabile.', buildTitle:'Genera release.', branchRelease:'Branch release: BT + incremento automatico.', channel:'Canale', version:'Versione', board:'Board', allBoards:'Tutte board', build:'Build release', registerTitle:'Carica backend.', registerCopy:'File locali devono essere caricati qui prima di comparire nel piano. BT non è default; ST diventa default board.', upload:'Registra firmware selezionati', planTitle:'Seleziona centraline.', planCopy:'Elenco firmware già presenti sul backend.', firmware:'Firmware', refreshFirmware:'Aggiorna elenco firmware', devices:'Centraline · una per riga', force:'Forza solo board assente.', createPlan:'Genera piano', applyTitle:'Conferma update.', planFirst:'Genera prima un piano.', apply:'Assegna firmware OTA', configuration:'CONFIGURAZIONE', settingsTitle:'Parametri dashboard.', apiKey:'API key Sense Square', apiKeyCopy:'Salvata solo nella memoria di questo browser.', projectPath:'Percorso progetto firmware', saveSettings:'Salva configurazione', close:'Chiudi', keyReady:'API KEY · READY', keyMissing:'API KEY · INSERISCI', pathReady:'Progetto disponibile.', pathMissing:'Cartella progetto assente.', buildWorking:'Build in corso. Attendere compilazione.', remoteCount:'Elenco backend aggiornato: {count} firmware.', planReady:'Piano pronto: {count} centraline. Conferma browser per assegnare {firmware}.', confirmApply:'Assegnare firmware OTA alle centraline del piano?', savedSettings:'Configurazione salvata.' },
  en: { heroLead:'Build, register and update devices with a verifiable plan.', buildTitle:'Create release.', branchRelease:'Branch release: BT + automatic increment.', channel:'Channel', version:'Version', board:'Board', allBoards:'All boards', build:'Build release', registerTitle:'Upload to backend.', registerCopy:'Local files must be uploaded here before they appear in the plan. BT is not default; ST becomes board default.', upload:'Register selected firmware', planTitle:'Select devices.', planCopy:'Firmware already available on the backend.', firmware:'Firmware', refreshFirmware:'Refresh firmware list', devices:'Devices · one per line', force:'Force only missing board.', createPlan:'Create plan', applyTitle:'Confirm update.', planFirst:'Create a plan first.', apply:'Assign OTA firmware', configuration:'CONFIGURATION', settingsTitle:'Dashboard settings.', apiKey:'Sense Square API key', apiKeyCopy:'Saved only in this browser storage.', projectPath:'Firmware project path', saveSettings:'Save settings', close:'Close', keyReady:'API KEY · READY', keyMissing:'API KEY · ENTER', pathReady:'Project folder available.', pathMissing:'Project folder missing.', buildWorking:'Build running. Wait for compilation.', remoteCount:'Backend list refreshed: {count} firmware.', planReady:'Plan ready: {count} devices. Confirm in browser to assign {firmware}.', confirmApply:'Assign OTA firmware to devices in this plan?', savedSettings:'Settings saved.' }
};
function language(){ const chosen=$('language').value; return chosen === 'auto' ? (navigator.language || 'it').toLowerCase().startsWith('it') ? 'it' : 'en' : chosen; }
function t(key, values={}){ return Object.entries(values).reduce((text,[name,value])=>text.replace(`{${name}}`,value), strings[language()][key] || key); }
function translate(){ document.documentElement.lang=language(); document.querySelectorAll('[data-i18n]').forEach(node=>node.textContent=t(node.dataset.i18n)); }
const out = (value) => $('output').textContent = typeof value === 'string' ? value : JSON.stringify(value, null, 2);
async function request(path, data) { const res = await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}); const body = await res.json(); if(!res.ok) throw new Error(body.error || 'Request failed'); return body; }
async function get(path) { const res = await fetch(path); const body = await res.json(); if(!res.ok) throw new Error(body.error || 'Request failed'); return body; }
function selectedReleases(){ return [...document.querySelectorAll('.release input:checked')].map(x=>x.value); }
function planFirmware(){ return $('plan-firmware').value; }
function populatePlan(){ const previous=planFirmware(), select=$('plan-firmware'); select.innerHTML=''; for(const name of remoteReleases) select.insertAdjacentHTML('beforeend',`<option value="${name}">${name}</option>`); if(remoteReleases.includes(previous)) select.value=previous; }
function populateLocal(releases){ const list=$('releases'); list.innerHTML=''; for(const name of releases) list.insertAdjacentHTML('beforeend',`<label class="release"><input type="checkbox" value="${name}">${name}</label>`); }
async function refresh(){ const status=await get('/api/status'); $('settings').textContent=status.api_key_configured?t('keyReady'):t('keyMissing'); $('project-path').value=status.project_root; $('path-status').textContent=status.project_root_exists?t('pathReady'):t('pathMissing'); populateLocal(status.releases); }
async function refreshRemote(){ const body=await get('/api/remote-firmwares'); remoteReleases=body.releases; populatePlan(); return remoteReleases.length; }
async function restoreBrowserKey(){ const key=localStorage.getItem('ota-dashboard-api-key'); if(key) await request('/api/config',{api_key:key}); }
$('language').value=localStorage.getItem('ota-dashboard-language') || 'auto';
$('language').onchange=()=>{ localStorage.setItem('ota-dashboard-language',$('language').value); translate(); refresh().catch(e=>out('ERROR: '+e.message)); };
$('settings').onclick=()=>{ $('api-key').value=localStorage.getItem('ota-dashboard-api-key') || ''; $('settings-dialog').showModal(); };
$('save-config').onclick=async(event)=>{ event.preventDefault(); try{ const key=$('api-key').value.trim(); if(key) localStorage.setItem('ota-dashboard-api-key',key); const body={project_root:$('project-path').value.trim()}; if(key) body.api_key=key; await request('/api/config',body); $('settings-dialog').close(); await refresh(); await refreshRemote(); out(t('savedSettings')); }catch(e){out('ERROR: '+e.message)} };
$('branch-release').onchange=()=>{ const active=$('branch-release').checked; $('channel').disabled=active; $('version').disabled=active; };
$('build').onclick=async()=>{ try{ out(t('buildWorking')); const env=$('environment').value; const body=await request('/api/build',{branch_release:$('branch-release').checked,channel:$('channel').value,version:$('version').value,environments:env?[env]:[]}); out(body.output); populateLocal(body.releases); }catch(e){out('ERROR: '+e.message)} };
$('upload').onclick=async()=>{ try{ const body=await request('/api/upload',{firmwares:selectedReleases()}); await refreshRemote(); out(body); }catch(e){out('ERROR: '+e.message)} };
$('remote-refresh').onclick=async()=>{ try{ out(t('remoteCount',{count:await refreshRemote()})); }catch(e){out('ERROR: '+e.message)} };
$('plan').onclick=async()=>{ try{ const centraline=$('centraline').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean); const body=await request('/api/plan',{firmware:planFirmware(),centraline,force:$('force').checked}); planId=body.plan_id; $('apply').disabled=false; $('apply-copy').textContent=t('planReady',{count:body.plan.devices.length,firmware:body.plan.target_firmware}); out(body.plan); }catch(e){out('ERROR: '+e.message)} };
$('apply').onclick=async()=>{ try{ if(!confirm(t('confirmApply'))) return; out(await request('/api/apply',{plan_id:planId})); }catch(e){out('ERROR: '+e.message)} };
translate(); restoreBrowserKey().then(()=>Promise.all([refresh(),refreshRemote()])).catch(e=>out('ERROR dashboard: '+e.message));
